import type { Metadata } from "next";
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    Show,
    UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/mode-toggle";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

import Link from "next/link";
import {
    NavigationMenu,
    NavigationMenuList,
    NavigationMenuItem,
    NavigationMenuLink,
    navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ClerkProvider>
                        <div className="w-full">
                            <header className="fixed inset-x-0 top-0 z-50">
                                <NavigationMenu className="w-full px-4 py-3">
                                    <NavigationMenuList className="rounded-xl border bg-background/85 p-1 px-5 shadow-lg backdrop-blur">
                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <Link href="/products">
                                                    Products
                                                </Link>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>
                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <Link href="/cart">Cart</Link>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>
                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <Link href="/orders">
                                                    Orders
                                                </Link>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>
                                        <NavigationMenuItem>
                                            <ModeToggle></ModeToggle>
                                        </NavigationMenuItem>

                                        <Show when="signed-out">
                                            <NavigationMenuItem>
                                                <NavigationMenuLink
                                                    asChild
                                                    className={navigationMenuTriggerStyle()}
                                                >
                                                    <SignInButton></SignInButton>
                                                </NavigationMenuLink>
                                            </NavigationMenuItem>
                                            <NavigationMenuItem>
                                                <NavigationMenuLink
                                                    asChild
                                                    className={navigationMenuTriggerStyle()}
                                                >
                                                    <SignUpButton></SignUpButton>
                                                </NavigationMenuLink>
                                            </NavigationMenuItem>
                                        </Show>
                                        <Show when="signed-in">
                                            <NavigationMenuItem>
                                                <UserButton></UserButton>
                                            </NavigationMenuItem>
                                        </Show>
                                    </NavigationMenuList>
                                </NavigationMenu>
                            </header>
                            {children}
                            <Toaster
                                richColors
                                closeButton
                                position="top-right"
                            />
                        </div>
                    </ClerkProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
