import type { Metadata } from "next";
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    Show,
    UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/mode-toggle";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
    NavigationMenu,
    NavigationMenuList,
    NavigationMenuItem,
    NavigationMenuLink,
    navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ClerkProvider>
                        <div className="w-full">
                            <NavigationMenu className="w-full">
                                <NavigationMenuList>
                                    {/* Theme Toggle */}
                                    <NavigationMenuItem>
                                        <ModeToggle></ModeToggle>
                                    </NavigationMenuItem>

                                    <Show when="signed-out">
                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <SignInButton></SignInButton>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>
                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <SignUpButton></SignUpButton>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>
                                    </Show>
                                    <Show when="signed-in">
                                        <NavigationMenuItem>
                                            <UserButton></UserButton>
                                        </NavigationMenuItem>
                                    </Show>
                                </NavigationMenuList>
                            </NavigationMenu>
                            {children}
                        </div>
                    </ClerkProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
